DEFAULT_ANALYSIS_DEPTH = 14
DEFAULT_ANALYSIS_TIME_LIMIT_MS = 350

MOVE_QUALITY_EXCELLENT = "excellent"
MOVE_QUALITY_GOOD = "good"
MOVE_QUALITY_INACCURACY = "inaccuracy"
MOVE_QUALITY_MISTAKE = "mistake"
MOVE_QUALITY_BLUNDER = "blunder"

ALL_MOVE_QUALITIES = {
    MOVE_QUALITY_EXCELLENT,
    MOVE_QUALITY_GOOD,
    MOVE_QUALITY_INACCURACY,
    MOVE_QUALITY_MISTAKE,
    MOVE_QUALITY_BLUNDER,
}
